export const ROUTES = {
    HOME: 'home',
    LOGIN: 'login',
    EMPLOYEE_LIST: 'employee/list',
    EMPLOYEE: 'employee',
    EMPLOYEE_VIEW: 'employee/view',
    USER_LIST: 'user/list',
    USER: 'user',
    USER_VIEW: 'user/view',
    JOB_TITLE_LIST: 'job-title/list',
    JOB_TITLE: 'job-title',
    DEPARTMENT_LIST: 'department/list',
    DEPARTMENT: 'department',
    ATTENDANCE_LIST: 'attendance/list',
    ATTENDANCE: 'attendance',
    ATTENDANCE_VIEW: 'attendance/view',
    SALARY_LIST: 'salary/list',
    SALARY: 'salary',
    SALARY_VIEW: 'salary/view',
    PERMISSIONS: 'permissions',
    PAGE_NOT_FOUND: '404',
    ACCESS: 'access',
  };
  